{
 "title": "Kubernetes Resource Right-Sizing (CPU & Memory)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info,namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster RAM requests / allocatable, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",namespace!=\"\"})\n/\nscalar(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster RAM requests / allocatable, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",namespace!=\"\"})\n/\nscalar(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM headroom, %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  100 *\n  sum(kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",namespace!=\"\"})\n  /\n  scalar(sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU requests / allocatable, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",namespace!=\"\"})\n/\nscalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU limits / allocatable, %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",namespace!=\"\"})\n/\nscalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU headroom, %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  100 *\n  sum(kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",namespace!=\"\"})\n  /\n  scalar(sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% RAM requests / allocatable per node",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (label_cloud_google_com_compute_class) (\n  (\n    label_replace(\n      node_memory_MemAvailable_bytes\n      * on (instance) group_left(nodename) node_uname_info,\n      \"node\", \"$1\", \"nodename\", \"(.*)\"\n    )\n  )\n  * on (node) group_left(label_cloud_google_com_compute_class)\n    max by (node, label_cloud_google_com_compute_class) (\n      kube_node_labels{label_cloud_google_com_compute_class!=\"\"}\n    )\n)\n/\nsum by (label_cloud_google_com_compute_class) (\n  kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}\n  * on (node) group_left(label_cloud_google_com_compute_class)\n    max by (node, label_cloud_google_com_compute_class) (\n      kube_node_labels{label_cloud_google_com_compute_class!=\"\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU requests / allocatable per node",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum by (label_cloud_google_com_compute_class) (\n  (\n    kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",namespace!=\"\"}\n    * on (namespace,pod) group_left(node)\n      kube_pod_info{node!=\"\"}\n  )\n  * on (node) group_left(label_cloud_google_com_compute_class)\n    max by (node, label_cloud_google_com_compute_class) (\n      kube_node_labels{label_cloud_google_com_compute_class!=\"\"}\n    )\n)\n/\nsum by (label_cloud_google_com_compute_class) (\n  kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}\n  * on (node) group_left(label_cloud_google_com_compute_class)\n    max by (node, label_cloud_google_com_compute_class) (\n      kube_node_labels{label_cloud_google_com_compute_class!=\"\"}\n    )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top nodes by Memory requests / allocatable, %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 *\n  sum by (node) (\n    kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",namespace!=\"\"}\n    * on (namespace,pod) group_left(node)\n      kube_pod_info{node!=\"\"}\n  )\n  /\n  sum by (node) (\n    kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"}\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top nodes by CPU requests / allocatable, %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 *\n  sum by (node) (\n    kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",namespace!=\"\"}\n    * on (namespace,pod) group_left(node)\n      kube_pod_info{node!=\"\"}\n  )\n  /\n  sum by (node) (\n    kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"}\n  )\n)\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top namespaces by Memory requests / cluster allocatable, %",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 * sum by (namespace) (kube_pod_container_resource_requests{resource=\"memory\",namespace!=\"\"})\n  / scalar(sum(kube_node_status_allocatable{resource=\"memory\"}))\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top namespaces by CPU requests / cluster allocatable, %",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  100 * sum by (namespace) (kube_pod_container_resource_requests{resource=\"cpu\",namespace!=\"\"})\n  / scalar(sum(kube_node_status_allocatable{resource=\"cpu\"}))\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Top pods by restarts + OOMKilled flag (24h/7d)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(\n  30,\n  sum by (namespace,pod) (\n    increase(kube_pod_container_status_restarts_total{namespace!=\"\",container!=\"POD\"}[24h])\n  )\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (namespace,pod) (\n  increase(kube_pod_container_status_restarts_total{namespace!=\"\",container!=\"POD\"}[7d])\n)\nand on (namespace,pod)\ntopk(\n  30,\n  sum by (namespace,pod) (\n    increase(kube_pod_container_status_restarts_total{namespace!=\"\",container!=\"POD\"}[24h])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,pod) (\n  max_over_time(\n    kube_pod_container_status_last_terminated_reason{\n      namespace!=\"\",container!=\"POD\",reason=\"OOMKilled\"\n    }[24h]\n  )\n)\nand on (namespace,pod)\ntopk(\n  30,\n  sum by (namespace,pod) (\n    increase(kube_pod_container_status_restarts_total{namespace!=\"\",container!=\"POD\"}[24h])\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,pod) (\n  max_over_time(\n    kube_pod_container_status_last_terminated_reason{\n      namespace!=\"\",container!=\"POD\",reason=\"OOMKilled\"\n    }[7d]\n  )\n)\nand on (namespace,pod)\ntopk(\n  30,\n  sum by (namespace,pod) (\n    increase(kube_pod_container_status_restarts_total{namespace!=\"\",container!=\"POD\"}[24h])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top pods by CPU throttling ratio (5m)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  15,\n  sum by (namespace, pod, container) (\n    rate(container_cpu_cfs_throttled_periods_total{container!=\"POD\", namespace!=\"\", pod!=\"\", container!=\"\", container!=\"POD\"}[5m])\n  )\n  /\n  clamp_min(\n    sum by (namespace, pod, container) (\n      rate(container_cpu_cfs_periods_total{container!=\"POD\", namespace!=\"\", pod!=\"\", container!=\"\", container!=\"POD\"}[5m])\n    ),\n    1\n  )\n)",
     "legendFormat": "{{namespace}}/{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Top namespaces by safe memory waste vs peak (6h)",
   "type": "bargauge",
   "description": "Memory requests minus peak working set over the last 6 hours.\nShows how much memory (GiB) is safe to reduce even under observed peak usage.\nValues are calculated for Running pods only.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  clamp_min(\n    (\n      sum by (namespace) (\n        kube_pod_container_resource_requests{resource=\"memory\", namespace!=\"\"}\n        and on(namespace,pod)\n        (kube_pod_status_phase{phase=\"Running\"} == 1)\n      )\n      -\n      sum by (namespace) (\n        max_over_time(\n          container_memory_working_set_bytes{namespace!=\"\",pod!=\"\",container!=\"\",image!=\"\"}[6h]\n        )\n      )\n    ),\n    0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top namespaces by safe CPU waste vs peak (6h), mCPU",
   "type": "bargauge",
   "description": "Requests − peak CPU usage over the last 6h. Values show millicores that are safe to reduce even under observed peaks.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mCPU (m)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  clamp_min(\n    (\n      sum by (namespace) (\n        kube_pod_container_resource_requests{resource=\"cpu\", namespace!=\"\"}\n        and on(namespace,pod)\n        (kube_pod_status_phase{phase=\"Running\"} == 1)\n      )\n      -\n      sum by (namespace) (\n        max_over_time(\n          rate(container_cpu_usage_seconds_total{namespace!=\"\",pod!=\"\",container!=\"\",image!=\"\"}[2m])\n        [6h:]\n        )\n      )\n    ) * 1000,\n    0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Request vs Working Set (current), %",
   "type": "barchart",
   "description": "Relative deviation of memory requests from the current Working Set.\nCalculated as (Requests / Working Set − 1) × 100 for each pod/container.\n\nPositive values indicate over-requested memory (potential for optimization).\n\nNegative values indicate under-requested memory (risk of eviction / OOM under load).\n\nValues reflect the current state and do not account for historical peaks.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp(\n  (\n    (\n      sum by (pod, container) (\n        kube_pod_container_resource_requests{\n          namespace=\"$namespace\",\n          resource=\"memory\"\n        }\n        and on(pod)\n        (kube_pod_status_phase{phase=\"Running\"} == 1)\n      )\n      /\n      clamp_min(\n        sum by (pod, container) (\n          container_memory_working_set_bytes{\n            namespace=\"$namespace\",\n            pod!=\"\",\n            container!=\"\",\n            image!=\"\"\n          }\n        ),\n        100 * 1024 * 1024\n      )\n    ) - 1\n  ) * 100,\n  -100,\n  300\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Рекомендованные memory requests на основе P70 Working Set",
   "type": "table",
   "description": "Рекомендации по memory requests на основе P70 Working Set за 7 дней\n(+20% запас, округление до 32 MiB).\n\nПримечание:\nРекомендации даны per pod+container.\nДля единого request на Deployment рекомендуется\nориентироваться на максимальное значение среди реплик.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "ceil(\n  (1.2 * max by (pod, container) (quantile_over_time(0.70, container_memory_working_set_bytes{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[7d])) / 1024 / 1024)\n  / 32\n) * 32",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (pod, container) (\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    resource=\"memory\",\n    unit=\"byte\"\n  }\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рекомендованные memory limits на основе P95 Working Set",
   "type": "table",
   "description": "Рекомендации по memory limits на основе P95 Working Set за 7 дней\n(+20% запас, округление до 32 MiB).\n\nДля stateful и memory-spiky приложений (БД, очереди)\nрекомендуется использовать P99 вместо P95.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "ceil(\n  (1.2 * max by (pod, container) (quantile_over_time(0.95, container_memory_working_set_bytes{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[7d])) / 1024 / 1024)\n  / 32\n) * 32",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (pod, container) (\n  kube_pod_container_resource_requests{\n    namespace=\"$namespace\",\n    resource=\"memory\",\n    unit=\"byte\"\n  }\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU requests vs usage (delta)",
   "type": "barchart",
   "description": "Показатель отражает отклонение CPU requests от фактического потребления CPU\nдля каждого pod+container.\n\nФормула:\n(request / usage − 1) × 100\n\nИнтерпретация:\n> 0%  — CPU request завышен, можно снизить\n≈ 0%  — request подобран корректно\n< 0%  — потребление превышает request, риск CPU starvation\n\nМетрики:\n• CPU usage: rate(container_cpu_usage_seconds_total) с усреднением за 15 минут\n• CPU request: kube_pod_container_resource_requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "mCPU (m)" } },
   "targets": [
    {
     "expr": "topk(\n  30,\n  clamp_min(\n    (\n      sum by (pod, container) (kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"} and on(namespace,pod) (kube_pod_status_phase{phase=\"Running\"}==1))\n      -\n      sum by (pod, container) (max_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[2m])[6h:]))\n    ) * 1000,\n    0\n  )\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "underrequest/risk",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "mCPU (m)" } },
   "targets": [
    {
     "expr": "topk(\n  30,\n  clamp_min(\n    (\n      sum by (pod, container) (max_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[2m])[6h:]))\n      -\n      sum by (pod, container) (kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"} and on(namespace,pod) (kube_pod_status_phase{phase=\"Running\"}==1))\n    ) * 1000,\n    0\n  )\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Рекомендованные CPU requests (P70, pod + container)",
   "type": "table",
   "description": "Рекомендации по CPU requests для каждого pod+container на основе исторического потребления.\n\nМетодика:\n• P70 от CPU usage (rate 5m) за последние 7 дней\n• +20% запас (headroom)\n• перевод в mCPU и округление до 10m\n\nИнтерпретация:\n• request ниже рекомендованного → риск CPU starvation при конкуренции\n• request выше рекомендованного → избыточные резервы (waste)\n",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "mCPU (m)" } },
   "targets": [
    {
     "expr": "ceil(\n  (\n    1.2 * max by (pod, container) (\n      quantile_over_time(\n        0.70,\n        rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[5m])[7d:5m]\n      )\n    )\n  ) * 1000 / 10\n) * 10\n",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (pod, container) (\n  kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рекомендованные CPU limits (P95, pod + container)",
   "type": "table",
   "description": "Рекомендации по CPU limits для каждого pod+container на основе исторического потребления.\n\nМетодика:\n• P95 от CPU usage (rate 5m) за последние 7 дней\n• +20% запас (headroom)\n• перевод в mCPU и округление до 10m\n\nПримечание:\nCPU limits могут приводить к throttling. Для latency-sensitive сервисов\nчасто задают requests, а limits не ставят (или ставят существенно выше).",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "mCPU (m)" } },
   "targets": [
    {
     "expr": "ceil(\n  (\n    1.2 * max by (pod, container) (\n      quantile_over_time(\n        0.95,\n        rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod!=\"\",container!=\"\",image!=\"\"}[5m])[7d:5m]\n      )\n    )\n  ) * 1000 / 10\n) * 10",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max by (pod, container) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\",pod!=\"\",container!=\"\",resource=\"cpu\",unit=\"core\"}\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}